// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR78t4Ey6jn8xTLRtN7mMfdWp7WI9SLHE',
    appId: '1:405750070953:web:80b900c11007213025b3b8',
    messagingSenderId: '405750070953',
    projectId: 'wingtip-f03f3',
    authDomain: 'wingtip-f03f3.firebaseapp.com',
    storageBucket: 'wingtip-f03f3.firebasestorage.app',
    measurementId: 'G-HEZGG17JFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjetkBPhAUR7YX3udBX8vK_Adj7OMV-c4',
    appId: '1:405750070953:android:d90f4890093fd50c25b3b8',
    messagingSenderId: '405750070953',
    projectId: 'wingtip-f03f3',
    storageBucket: 'wingtip-f03f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRgRoQvL_HKu1nv1NZwYvZF4LMF1Bmhss',
    appId: '1:405750070953:ios:e6439bcd220b6d6d25b3b8',
    messagingSenderId: '405750070953',
    projectId: 'wingtip-f03f3',
    storageBucket: 'wingtip-f03f3.firebasestorage.app',
    iosBundleId: 'com.ooheynerds.wingtip',
  );
}
